name: Bug Report
description: Report a bug or unexpected behavior of the SIR 3S Toolkit
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the form below as completely as possible.

  - type: input
    id: summary
    attributes:
      label: Short Summary
      description: Brief description of the issue
      placeholder: e.g. Method GetValue() fails
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What did you do?
      placeholder: |
        1. Open model A
        2. Call `ExecCalculation(True)`
        3. Observe exception
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, sir3stoolkit version
      placeholder: e.g. Windows 11, Python 3.12, sir3stoolkit 90.15.1
    validations:
      required: false
