name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: e.g. Add support for exporting models

  - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
      description: Describe the context or use case
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Suggested Implementation (optional)
      description: Describe how this might work or look
    validations:
      required: false
