name: Build and Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest  # Windows Runner statt Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install project with dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,sphinx]

      - name: Set PYTHONPATH (Windows)
        run:  |
          echo "PYTHONPATH=${{ github.workspace }}\\src" >> $env:GITHUB_ENV

      - name: Generate rst files with sphinx-apidoc
        run: |
          sphinx-apidoc -o docs/source/references src/sir3stoolkit

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
